site_name: Receptenboek van Steven en Clara
theme:
   name: material
   color_mode: auto
   font:
     text: Fira Sans
   palette:
     scheme: default
     primary: teal
   features:
     - search.suggest
     - navigation.path
     - content.code.copy
plugins:
  - search
  - exclude-search:
      exclude:
        - Overzicht.md
  - tags
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.snippets    
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/javascript.js
